### ISSUE TITLE
How could I use your library?

### ISSUE THREAD

**Issue by hedgemaster29** [msng/gmo-payment-gateway#1]
初めまして。

gmopaymentライブラリーを調査する過程で貴下の結果物を探すようになりました。 ほぼ完璧な結果だと思いますが、どう利用するのかわかりません。

利用サンプルを送っていただければ大変助かります。

どうぞ、よろしくお願いいたします。

**Comment by msng** [comment]
確認が遅くなり申し訳ありません。

必要に応じて利用できるよう公開してはありますが、
このライブラリの利用についてのサポートは行っていません。

ご理解いただければと思います。
